volumes:
  pgdatasource:

services:
  db:
    image: postgres
    container_name: myOrbitTool-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    # volumes:
    #   - pgdatasource:/var/lib/postgresql/data

  api:
    build: api/
    container_name: myOrbitTool-api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - app-network
    env_file:
      - .env
  # volumes:
  #   - type: bind
  #     source: ./api
  #     target: /app

  ui:
    build: ui/
    tty: true
    container_name: myOrbitTool-ui
    depends_on:
      - "api"
    ports:
      - "3000:3000"
    networks:
      - app-network
    env_file:
      - .env
  # Uncomment the following lines to enable live code updates
  # volumes:
  #   - type: bind
  #     source: ./ui
  #     target: /app
  #   - /app/node_modules

networks:
  app-network:
    driver: bridge
